### ISSUE TITLE
sh make.sh error

### ISSUE THREAD

**Issue by yaodonggggggg** [soeaver/Parsing-R-CNN#1]
gcc: error: /home/faustino/.local/share/Trash/files/Parsing-R-CNN-master/parsingrcnn/model/nms/src/nms_cuda.c: 没有那个文件或目录
should i do make.sh first of all?then cd /tool ,do python train_net_multi_gpu.py?

**Comment by wadesunyang** [comment]
it means it didn't have the file nms_cuda.c,   so you can get this file from other faster-rcnn or mask-rcnn, such as  you can get it from "  https://github.com/jwyang/faster-rcnn.pytorch/tree/master/lib/model/nms/src " .

**Comment by yaodonggggggg** [comment]
> it means it didn't have the file nms_cuda.c, so you can get this file from other faster-rcnn or mask-rcnn, such as you can get it from " https://github.com/jwyang/faster-rcnn.pytorch/tree/master/lib/model/nms/src " .

thank you!!!

**Comment by wadesunyang** [comment]
if you run the train successfully, please tell me the step and we can discuss some questions about it , i'm interested in this project too, thank you.

**Comment by yaodonggggggg** [comment]
> if you run the train successfully, please tell me the step and we can discuss some questions about it , i'm interested in this project too, thank you.

I‘m sorry to say that i couldn’t train this model recently。 I must to try mask rcnn firstly because its steps are very clear in the homepage。
