### ISSUE TITLE
Steps to run single image inference

### ISSUE THREAD

**Issue by iamrishab** [soeaver/Parsing-R-CNN#16]
Can you please suggest the steps to run single image inference. I can see only test script is there. But I need a quick guide to setup a pipeline to take a single image and return the parsed segmentation.

**Comment by iamrishab** [comment]
I have customized the `test_net.py` and the dataloader with some additional changes here and there. Will create a pull request after some additional hardening and testing. Closing for now. Thanks!

**Comment by abhigoku10** [comment]
@iamrishab  can you share your single image inference , it will be helpful !!! thanks in advance

**Comment by bhargavkumar559** [comment]
> 

Hey,can you share the inference code for single image. Thank you

**Comment by xddlj** [comment]
can you share the inference code，thanks！
